### ISSUE TITLE
add command to store/sync a given data size onto disk

### ISSUE THREAD

**Issue by tomcucinotta** [tomcucinotta/distwalk#3]
in addition to the process, forward and reply commands, the distwalk should also support the possibility to specify a disk write operation that should be sync()ed on disk, before letting the next command be executed (e.g, reply or forward); similarly, we should have a disk read operation; for both, we should be able to specify the amount of data to write (alongside with the actual data to write, possibly) or read (causing that amount of data to be returned with a reply) as a parameter of the command.

**Comment by deRemo** [comment]
Working on this

**Comment by deRemo** [comment]
commit 287d3e5611c496c000f7b5ea4ef83035dd38ccf2
commit 50dc7838635f06166b1d302c7c9e3c8b6b0e6bfd
