### ISSUE TITLE
client hangs on FORWARD towards wrong IP:host

### ISSUE THREAD

**Issue by tomcucinotta** [tomcucinotta/distwalk#45]
When dw_client asks dw_node to forward to a wrong IP:host, it hangs forever. For example:
```
./dw_node
./dw_client -F :7895
```
Here, even though dw_node catches the connect() failure, it does not notify the client anyway (error message, or connection close), so the client keeps waiting forever.

**Comment by tomcucinotta** [comment]
we might deal with this:
- by using a per-request timeout on the client-side (when it fires, mark the request as failed);
- by letting dw_node send the client a special REPLY for the interested req_id with an error-code;
- by letting dw_node just close the connection.

The 3rd solution above seems the easiest, however, in case the "client" is another dw_node who is just forwarding a client's request, closing the dw_node <-> dw_node connection might be an over-reaction to a single FORWARD that could not connect().
Therefore, I'd lean towards both of the first solutions above together (timeouts should always be there in a real distributed application, nobody should ever hang waiting forever, plus we could reply with an error to the interested client, so that it may know and take action earlier than the timeout).

**Comment by deRemo** [comment]
Moreover, Solution 3 is not suitable for multi-forward scenarios because the connection should remain open, especially when the number of acknowledgments (i.e., n_acks) is less than the number of forwarded nodes, as the command may succeed nonetheless.
