### ISSUE TITLE
add the possibility to use per-client dedicated threads as an option to node.c

### ISSUE THREAD

**Issue by tomcucinotta** [tomcucinotta/distwalk#5]
Currently, node.c has only a single thread with an epoll()-based loop.
This is about adding the possibility to use per-client dedicated threads as an option to node.c.

**Comment by tomcucinotta** [comment]
Currently, node.c has only a single thread with an epoll()-based loop.
This is about adding the possibility to use per-client dedicated threads as an option to node.c.

**Comment by deRemo** [comment]
Working on this

**Comment by deRemo** [comment]
Important commits:

ea7abc93896bfe10ce472abc32c1f47948a5e8a5
3e8ae4fc777573fe9d22c968764a82e7700b9bbb
991dc478f730077b3c6c0f72c747834322b4ec00
726f9c7f2900b980461ea4fd00b141a4fff33ad9
4de8238b63d0f97f8f0cab329aa350447faf18f0
