### ISSUE TITLE
complete FORWARD

### ISSUE THREAD

**Issue by tomcucinotta** [tomcucinotta/distwalk#9]
FORWARD was never finished in node.c, and cannot be used at the moment;
it needs to be completed with connect() to the forwarding nodes, to be added to sock_info[];
this needs to be done going through epoll_wait(), to avoid blocking the thread waiting for connection establishment

**Comment by tomcucinotta** [comment]
@deRemo, have a look at the forward branch (sketch / incomplete):
https://github.com/tomcucinotta/distwalk/tree/forward

**Comment by deRemo** [comment]
First working prototype from 1613dec

**Comment by tomcucinotta** [comment]
Seems we have a working FORWARD in commit 1613decd. However, for now it blocks the client thread waiting for the response from the forwarded server.
